### PR TITLE
Update Bevy to 0.11

### PR DESCRIPTION
**Pull request by paul-hansen**
The only thing I wasn't sure about is with input mocking, .11 adds a [`window`](https://docs.rs/bevy/latest/bevy/input/mouse/struct.MouseWheel.html#structfield.window) field to input events that I just populated with Entity::PLACEHOLDER when sending events because our test environment doesn't create a window so all the tests would fail trying to get a window.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Yep, placeholder is correct. 

Why do we need `TypePath` now?

**Comment by paul-hansen** [comment]
> Why do we need TypePath now?

This line was complaining without it:
https://github.com/Leafwing-Studios/leafwing-input-manager/blob/dfbe44b22fae01434737fb498dfb10d5ca20057d/src/plugin.rs#L146

If you remove the TypePath requirement from Actionlike, it gives this error:
```
error[E0277]: the trait bound `A: TypePath` is not satisfied
   --> src\plugin.rs:146:29
    |
146 |         app.register_type::<ActionState<A>>()
    |                             ^^^^^^^^^^^^^^ the trait `TypePath` is not implemented for `A`
    |
note: required for `ActionState<A>` to implement `GetTypeRegistration`
   --> src\action_state.rs:85:80
    |
85  | #[derive(Resource, Component, Clone, Debug, PartialEq, Serialize, Deserialize, Reflect)]
    |                                                                                ^^^^^^^ unsatisfied trait bound introduced in this `derive` macro
86  | pub struct ActionState<A: Actionlike> {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required by a bound in `App::register_type`
   --> D:\Packages\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.0\src\app.rs:816:29
    |
816 |     pub fn register_type<T: bevy_reflect::GetTypeRegistration>(&mut self) -> &mut Self {
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `App::register_type`
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider further restricting this bound
    |
82  | impl<A: Actionlike + bevy::reflect::TypePath> Plugin for InputManagerPlugin<A> {
    |                    +++++++++++++++++++++++++
```

I'm open to suggestions, was just added to get it to compile.

**Comment by paul-hansen** [comment]
Opened an issue as it seems like it might be an unintentional restriction since it isn't mentioned in migration guides: https://github.com/bevyengine/bevy/issues/9094

**Comment by alice-i-cecile** [comment]
Great; doesn't look like something we can work around here.

**Comment by alice-i-cecile** [comment]
Once bevy_egui ships I'll merge this and then cut a release. Thanks a ton!

**Comment by alice-i-cecile** [comment]
`bevy_egui` v0.21 is now live: once that's swapped over I'll merge this and cut a release <3

**Comment by paul-hansen** [comment]
Done, looking good to go on my end!

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
