### PR TITLE
Upgrade to Bevy 0.15.0

### PR DESCRIPTION
**Pull request by mnmaita**
Adopts #644

- Branched off [pcwalton:0.15-newer](https://github.com/pcwalton/leafwing-input-manager/tree/0.15-newer) and resolved conflicts with the `main` branch.
- Bumped `bevy_egui` version requirement to the latest compatible version.
- Set Bevy version requirement to 0.15.0.
- Replaced usage of the deprecated `SpriteBundle` with `Sprite` and `Transform` components.
- Applied system ordering suggestions from [this comment](https://github.com/Leafwing-Studios/leafwing-input-manager/pull/644#issuecomment-2527717209).

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
You all rock. This looks great. I'll prepare a release!

**Comment by mnmaita** [comment]
Just found a merge hiccup and I fixed that, but I couldn't fix the broken gamepad tests... It's either something I messed up during the merge process, or it could be that some of the latest changes in `main` have to be changed to be 0.15 compatible. I'll appreciate any help here!

**Comment by alice-i-cecile** [comment]
Can you ignore the tests for now? I think we should move forward as is and then fix the tests in follow-up.

**Comment by mnmaita** [comment]
Sure @alice-i-cecile, although I'm a bit worried since they seem to be checking the press status and the values of gamepad buttons and are failing to do so:

```
failures:

---- buttonlike_actions_can_be_pressed_and_released_when_button_value_set stdout ----
thread 'buttonlike_actions_can_be_pressed_and_released_when_button_value_set' panicked at tests\buttonlike.rs:195:5:
assertion failed: action_state.just_pressed(&TestAction::Throttle)

---- gamepad_button_value stdout ----
thread 'gamepad_button_value' panicked at tests\buttonlike.rs:103:5:
assertion `left == right` failed
  left: 0.0
 right: 1.0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    buttonlike_actions_can_be_pressed_and_released_when_button_value_set
    gamepad_button_value

test result: FAILED. 4 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

I tried fixing pcwalton's branch prior to merging main, and the system ordering suggestion fixed all test issues, which suggests there's some other new issue that popped up for gamepads.

I'll push a change to ignore them anyway if that's the way to go.

**Comment by alice-i-cecile** [comment]
Definitely share your concern: it's a blocking issue. I want to split it out though to be sure we can properly review and discuss the fix.

**Comment by mnmaita** [comment]
I forgot to test this with all features enabled 😓 I'll do another pass and fix the remaining failures as soon as I can.

**Comment by mnmaita** [comment]
@alice-i-cecile should be ready now, I ran all CI commands locally and they all pass. I took the liberty to adjust some doc comments to better fit the fact that Gamepads are now entities.

**Pull request merged**
