### PR TITLE
Add `ActionState::consume_all()` to consume all actions.

### PR DESCRIPTION
**Pull request by ndarilek**
## What was the problem?

Some state transitions (E.g. pause/unpause, menu transitions) need to nuke action states from orbit. It isn't enough to release them since, say, `just_pressed` might trigger if a UI and game action share a binding with a game action. Currently I manually consume actions if a binding to start/exit a menu conflicts with a game action, but this assumes a specific binding and doesn't allow for flexibility.

While disabling actions is also possible, it requires disabling/enabling multiple mappings at multiple transition points. I found it much easier to reason about clearing all action state on game pause/start/resume than ensuring that multiple UI menus manually disable and re-enable multiple action mappings.

## How did you fix it?

`ActionState::consume_all()` can be run at state transitions where action state should have a clean slate (I.e. transitioning from a menu to a game where bindings might be shared, crossing level boundaries where state changes might not correctly handle transitions, etc.)

### CODE REVIEW

**Comment by ndarilek** [comment]
Ugh, sorry, used the github CLI and that didn't correctly handle the template.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Fixed the template for you. Can you add a note to the RELEASES.md file?

**Comment by ndarilek** [comment]
Done, please let me know if you need it changed or recategorized.

**Comment by alice-i-cecile** [comment]
This change belongs in the `Usability` heading :) Once that's done I'll merge this for you.

**Comment by ndarilek** [comment]
Looks like those clippy errors aren't mine. Am I misreading the CI output? GitHub doesn't make it particularly accessible unfortunately.

Thanks.

**Comment by alice-i-cecile** [comment]
Not your errors. Looks like it's due to the new Rust version. I'll tackle them on my own, then merge this + Nile's PR and do a release tomorrow.

**Pull request merged**
