### PR TITLE
Add wasm32 build to ci (#636)

### PR DESCRIPTION
**Pull request by gak**
Fixes #599 #636

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thanks :) Let's see how this goes.

**Comment by gak** [comment]
Yaks shaved so far:

- Had to update to bevy_egui 0.29 because of a [wasm32 build error](https://github.com/mvlabat/bevy_egui/issues/300)
- [0.29](https://github.com/mvlabat/bevy_egui/compare/v0.28.0...v0.29.0#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R50) adds the `bevy_winit` feature which needs a rendering back-end to compile with, so I added the `bevy/wayland` feature when including `bevy_winit` when running ci.

**Comment by gak** [comment]
Finally! This took way too long. Hope it's acceptable.

**Comment by alice-i-cecile** [comment]
Awesome, thanks. Waiting for a bit due to being a breaking change with the dependency bump.

**Pull request merged**
