### PR TITLE
Update the dependencies to `bevy` 0.13 and `bevy_egui` 0.25

### PR DESCRIPTION
**Pull request by Shute052**
# Status

The contents of this complex PR have been split into PRs #465, #466, and #470.

# Objective

Update the dependencies to `bevy` 0.13 and `bevy_egui` 0.25 (unreleased).

## Solution

Updates for `bevy` 0.13 (passed all tests) and `bevy_egui` 0.25 (passed all tests).

`bevy_egui` now has an [PR #236](https://github.com/mvlabat/bevy_egui/pull/236) to update to `bevy` 0.13.
Unfortuanly, it is not yet updated to the new released bevy.
To address this, I temporarily use my forked version from the PR repo, fixing the problem.

## TODO

- [x] Remove the logger after the bug resolved
- [ ] Block on unreleased `bevy_egui` 0.25
- [ ] Document

## Relevant PRs

- [Bevy PR #10702: Update winit to 0.29](https://github.com/bevyengine/bevy/pull/10702)
- [Bevy PR #10859: `Input` → `ButtonInput`](https://github.com/bevyengine/bevy/pull/10859)
~~- [Bevy PR #11692: `KeyCode` → `PhysicalKey`](https://github.com/bevyengine/bevy/pull/11692)~~

## Migration Guide

- Both `KeyCode`-based logical keybindings and `ScanCode`-based physical keybindings are no longer supported; please migrate to:
  - `KeyCode` is now representing physical keybindings. 
  - `InputKind::KeyLocation` have been removed; please use `InputKind::PhysicalKey` instead.
  - `ScanCode` and `QwertyScanCode` have been removed; please use `KeyCode` instead:
    - All letter keys now follow the format `KeyCode::Key<Letter>`, e.g., `ScanCode::K` is now `KeyCode::KeyK`.
    - All number keys over letters now follow the format `KeyCode::Digit<Number>`, e.g., `ScanCode::Key1` is now `KeyCode::Digit1`.
    - All arrow keys now follow the format `KeyCode::Arrow<Direction>`, e.g., `ScanCode::Up` is now `KeyCode::ArrowUp`.

## Internal Changes

- `Input` has been renamed to `ButtonInput`.
- Replace `assert!` with `assert_eq!`.
- Simplify code logic.
- Fix typo in `axislike.rs`.

### `examples/twin_stick_controller.rs`

- `Ray3d::intersect_plane()` now take a `Plane2d` rather than a `Vec3` as the normal of the plane after the merge of [Bevy PR #10856](https://github.com/bevyengine/bevy/pull/10856)
- `add_state` has been renamed to `init_state` after the merge of [Bevy PR #11043](https://github.com/bevyengine/bevy/pull/11043)

### CODE REVIEW

**Comment by Shute052** [comment]
After reviewing the [Bevy PR #10702](https://github.com/bevyengine/bevy/pull/10702), it seems like `ScanCode` has been merged into `KeyCode`.

Could we consider merging ScanCode into KeyCode following the PR, and subsequently replace all instances of InputKind::Keyboard with InputKind::KeyLocation? Also, is it advisable to remove all code, examples, and documentation related to `ScanCode`s, `QwertyScanCode`s and physical keybindings?

**Comment by alice-i-cecile** [comment]
@TimJentzsch, I'd appreciate your guidance around what to do with `ScanCode`.

**Comment by Shute052** [comment]
It seems no longer we can use the logical key bindings layout like before, even use `InputKind::Keyboard(Key)`, because `Key` stores an actual inputed character for the letter buttons. For example, `KeyCode::W` need become `Key::Character(SmolStr(Repr::Static("W")))`, that is really terrible. And then:

```rust
let input_map = InputMap::new([
    (RunAction::Forward, Key::Character(SmolStr(Repr::Static("W")))),
    (RunAction::Backward, Key::Character(SmolStr(Repr::Static("S")))),
    (RunAction::Left, Key::Character(SmolStr(Repr::Static("A")))),
    (RunAction::Right, Key::Character(SmolStr(Repr::Static("D")))),
]);
```

And now it functions normally like before on US keyboard.
However, for French players, we have to add bindings for the "ZQSD" keys, "Цфыв" keys for Kyrgyz players, and so on.

**Comment by Shute052** [comment]
`ReceivedCharacter` also doesn‘t derive the `Copy`

**Comment by alice-i-cecile** [comment]
Yeah, my feeling is that we're going to need to drop support for `ScanCode` in this version, then work upstream in both Bevy and winit to try and build a useful abstraction.

**Comment by Shute052** [comment]
Used a temporary solution, sending a placeholder like 'Mocking' as a logical key, fixed the compilation erros and passed all tests

**Comment by Shute052** [comment]
Maybe I found a way to re-implement the logical key bindings, but it seems really breaking and ugly:
Remove `Copy` trait for `InputKind`, add `InputKind::Keyboard(Key)` for logical bindings, and replace all the previous `KeyCode` with `Key`.

For example:

`KeyCode::Key<Letter>` and `KeyCode::Digit<Number>` into `Key::Character("<Letter or Number>")`, e.g., `Key::Character("a or 7")

**Comment by Shute052** [comment]
> Maybe I found a way to re-implement the logical key bindings, but it seems really breaking and ugly: Remove `Copy` trait for `InputKind`, add `InputKind::Keyboard(Key)` for logical bindings, and replace all the previous `KeyCode` with `Key`.
> 
> For example:
> 
> `KeyCode::Key<Letter>` and `KeyCode::Digit<Number>` into `Key::Character("<Letter or Number>")`, e.g., `Key::Character("a or 7")`
> 
> This change is kind of a mess and could easily lead to some unintended chaos. Definitely needs a makeover.

This is really terrible after the test.

The situation is:
- If you press any letter keys, e.g., W key and then you will get a `KeyboardInput(logical_key: "w")`, an expected lowercase w letter.
- However, if CapsLock is activated or Shift is pressing, like normal text input, you will get a `KeyboardInput(logical_key: "W")`, **an UPPERCASE W LETTER**!

**Comment by TimJentzsch** [comment]
> @TimJentzsch, I'd appreciate your guidance around what to do with `ScanCode`.

I think it's safe to remove, to my understanding the new `KeyCode` provided by winit is pretty much the same thing, just with different naming.

As for logical keybindings: I think it makes sense that they are a string now.
These probably only make sense when you want the character being typed to be the same as you display on the screen.
If you implement a controls setting in your game, you probably want the user to type the keys they want to use for the binding.
Then you could perhaps safe the keycode for the thing to check for on press, but display the logical key in the UI.

**Comment by Shute052** [comment]
Most functionality of new logical key bindins system has been complete, but only one problem:

ActionState::just_released(Key) will be reported in the next frame when reporting ActionState::pressed(Key) even we are holding it

**Comment by Shute052** [comment]
> Most functionality of new logical key bindings system has been completed, but only one problem:新的逻辑键绑定系统的大部分功能已经完成，但只有一个问题：
> 
> ActionState::just_released(Key) will be reported in the next frame when reporting ActionState::pressed(Key) even we are holding it当我们按住按键时，在下一帧中报告按键状态：：按下按键时，会报告按键状态：：just_released（按键）

Certainly! Here's an improved version:

It seems that the issue is not on my end. While testing, I noticed that `Events<KeyboardInput>` doesn't consistently report the button as pressed every frame, even when I'm holding it.

**Comment by Shute052** [comment]
> It seems that the issue is not on my end. While testing, I noticed that `Events<KeyboardInput>` doesn't consistently report the button as pressed every frame, even when I'm holding it.

## Logs



## Reproduction Case

```rust
use bevy::prelude::*;
use leafwing_input_manager::prelude::*;

#[derive(Actionlike, PartialEq, Eq, Clone, Copy, Hash, Debug, Reflect)]
enum Action {
    Run,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(InputManagerPlugin::<Action>::default())
        .add_systems(Startup, spawn)
        .add_systems(Update, check_state)
        .run()
}

fn spawn(mut commands: Commands) {
    let input_map = InputMap::new([
      (Action::Run, UserInput::from(Key::Character("s".into()))),
    ]);
    commands.spawn(InputManagerBundle {
        input_map,
        ..default()
    });
}

fn check_state(action_state: Query<&ActionState<Action>>) {
    for state in action_state.iter() {
        if state.pressed(&Action::Run) {
            info!("Got Pressed");
        }
        if state.just_released(&Action::Run) {
            info!("Got JustReleased");
        }
    }
}
```

## Internal Library Codes

You could check the recently updated code, or just look at the following snippets:

The system to read the data from `Events<KeyboardInput>`:

```rust
pub fn update_action_state<A: Actionlike>(
  mut keyboard_events: EventReader<KeyboardInput>,
  // ...Other system params
) {
  // Have to be Option value due to the requirement of a dependency.
  let keyboard_events: Option<Vec<KeyboardInput>> = Some(keyboard_events.read().cloned().collect());
  
  info!("KeyboardEvents: {keyboard_events:?}");

  // The InputStreams is used to update the ActionState.
  let input_streams = InputStreams {
    keyboard_events: keyboard_events.clone(),
  };
  
  action_state.update(input_map.which_pressed(&input_streams, *clash_strategy));
}
```

And the `InputMap::which_pressed()` is handling the `InputStreams`:

```rust
pub fn which_pressed(
    &self,
    input_streams: &InputStreams,
    // Unrelated params
) -> HashMap<A, ActionData> {
    let mut action_data = HashMap::new();

    // Generate the raw action presses
    for (action, input_vec) in self.iter() {
        let mut action_datum = ActionData::default();

        for input in input_vec {
            let pressed = input_streams.input_pressed(input);

            // TODO: for testing
            info!("Is action_datum pressed? {pressed}");
            if pressed {
                action_datum.state = ButtonState::JustPressed;
            }
        }

        action_data.insert(action.clone(), action_datum);
    }

    action_data
}
```
And the `InputStreams::input_pressed` handles the `Key` of the `KeyboardInput`:

```rust
pub fn input_pressed(&self, button: InputKind) -> bool {
  match button {
    // The InputKind for `bevy::input::keyboard::Key`
    InputKind::Keyboard(key_specified) => self
      .keyboard_events
      .clone()
      .map(|events| {
        events.iter().any(|kb_input| {
          let key_input = &kb_input.logical_key;
          match (key_specified.clone(), key_input.clone()) {
              (Key::Character(text_specified), Key::Character(text_input)) => {
                  let ret = text_specified == text_input;

                  info!(
                      "Logical Key: specified {}, input {}, eq {}",
                      text_specified, text_input, ret
                  );
                  ret
              }
              (_, logical_key) => key_specified == logical_key,
          }
        })
      })
      .unwrap_or_default(),
    // ...Other kinds of input
  }
}
```

**Comment by Shute052** [comment]
@alice-i-cecile
Is there a bug, or did I overlook something in handling `EventReader`?

**Comment by Shute052** [comment]
At the start, the compiler ate up quite a chunk of my time, but all problems are ironed out now. Currently, patiently waiting for the upstream to roll out the next set of updates

**Comment by alice-i-cecile** [comment]
Thanks a ton! I don't have the time to tackle this *right* now, but I promise I'll come back to this in earnest both before and after Bevy's release.

**Comment by Shute052** [comment]
Sure, I also want in hope to the release of Bevy 0.13 too, so I thought I'd lend a hand for any way I can

**Comment by Shute052** [comment]
The re-implemented logical key bindings pose a significant breaking, but not from my ends.

To specific, both `KeyboardInput` and `ReceivedCharacter` behaviors starkly deviate from the functionality of `KeyCode`s, rendering the logical keybindings system unsuitable for gaming applications.

Consider the common WASD actions for player movement:
- When holding down the W key initially and subsequently pressing the S key, the `KeyCode`s are expectedly reported as `WWWWSWSWSWSWSWS`, aligning seamlessly with gaming conventions.
- However, the alternative methods simply provide `WWWWSSSSSSS` as default KeyboardEvent sequences, a gross departure from the desired gaming input format.

Perhaps it would be advisable to reconsider the complete removal of logical key bindings for logical consistency.

**Comment by Shute052** [comment]
I discovered numerous instances where std functions could simplify and dedepulicate existing ones, as evident from the changes made in commit [9404645](https://github.com/Leafwing-Studios/leafwing-input-manager/pull/463/commits/9404645c71e3b27ef54b053445c390b6ab113c02). Would it be advisable for me to make new PR remake these changes?

**Comment by alice-i-cecile** [comment]
Keep working here; I'll review by diff, rather than by commit.

**Comment by Shute052** [comment]
The new commit refactors the logic for simplification and improved performance.

Note that the new `button_pressed()` and `input_value()` computation for both `MouseMotion` and `MouseWheel` may seem confusing.
Refer to the [Decompiled Code](https://rust.godbolt.org/z/Ms6YE86r9) for insights.
These changes aim to assist the compiler in optimizing the code towards just a more efficient `f64` accumulation, ultimately reducing executable size.

**Comment by Shute052** [comment]
Note that the new `button_pressed()` and `input_value()` computation for both `MouseMotion` and `MouseWheel` may seem confusing.
Refer to the [Decompiled Code](https://rust.godbolt.org/z/Ms6YE86r9) for insights.
These changes aim to assist the compiler in optimizing the code towards just a more efficient `f64` accumulation, ultimately reducing executable size.
In my test with 10k random directions and events, the new version showed a roughly 1-3% improvement.

**Comment by alice-i-cecile** [comment]
FYI, plan for tomorrow is to cut a release off of main for Bevy 0.12, and then come to this PR, do a final review pass, and then cut a second release for 0.13 :)

**Comment by Seldom-SE** [comment]
With
```toml
[dependencies]
bevy = { version = "0.13.0", default-features = false }

[dependencies.leafwing-input-manager]
git = "https://github.com/Shute052/leafwing-input-manager"
rev = "2b069dd"
default-features = false
```
I get
```
error[E0432]: unresolved import `bevy::asset`
  --> /home/seldom/.cargo/git/checkouts/leafwing-input-manager-a0e9919cdd1c7500/2b069dd/src/input_map.rs:10:11
   |
10 | use bevy::asset::Asset;
   |           ^^^^^ could not find `asset` in `bevy`

error: cannot determine resolution for the derive macro `Asset`
  --> /home/seldom/.cargo/git/checkouts/leafwing-input-manager-a0e9919cdd1c7500/2b069dd/src/input_map.rs:75:55
   |
75 |     Resource, Component, Debug, Clone, PartialEq, Eq, Asset, Reflect, Serialize, Deserialize,
   |                                                       ^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports
```
Minimal repro: https://github.com/Seldom-SE/testetst/tree/bebb52cbfc4d5cddad7bffe36a24eef38919126c

**Comment by Shute052** [comment]
> Minimal repro: https://github.com/Seldom-SE/testetst/tree/bebb52cbfc4d5cddad7bffe36a24eef38919126c

In your configuration, 

The issue was identified in the configuration, where bevy specifies:

```rust
#[cfg(feature = "bevy_asset")]
pub mod asset {
    //! Functions for loading and storing assets and resources for Apps.
    pub use bevy_asset::*;
}
```

And in your configuration, the default features have been disabled and the `bevy_asset` feature flag doesn't enabled specifically.

The problem can also be reproduced with the latest main branch or even after merging PR #421 (which addresses a bug related to the absence of the `egui` flag) with Bevy version 0.12.1.

**Comment by Shute052** [comment]
Another solution could be to make the `Asset` derive for `InputMap` optional, catering to those who prefer not to enable the `bevy_asset` feature.

**Comment by alice-i-cecile** [comment]
> Another solution could be to make the `Asset` derive for `InputMap` optional, catering to those who prefer not to enable the `bevy_asset` feature.

We should do that, and feature gate it.

**Comment by alice-i-cecile** [comment]
Oh, great idea with the table!

**Comment by Shute052** [comment]
Perhaps we could splitting the version table and the `asset` feature gate into a separate PR for the 0.12 release of this crate?

**Comment by alice-i-cecile** [comment]
> Perhaps we could splitting the version table and the `asset` feature gate into a separate PR for the 0.12 release of this crate?

Yep, I'd be happy with that. If you do, add a changelog entry and bump the version to 0.12.1 please.

**Comment by Shute052** [comment]
The contents of this complex PR have been split into PRs #465, #466, and #470.

**Pull request closed without merging**
