### PR TITLE
Add CI testing for all feature flag combinations and fix all reported errors

### PR DESCRIPTION
**Pull request by Shute052**
# Objective

Make sure we thoroughly test all feature-related code and updates.

## Solution

Cover all combinations of features our crate offers when running CI tests for `clippy`, ~~`doc-check`,~~ `doc-test`, `test`, and `compile-check`.

For instance, given the current existence of four features: `asset`, `ui`, `block_ui_interactions`, and `egui`, the new CI testing will include scenarios like:

- Testing with `--no-default-features`
- Testing with `--all-features`
- Testing with individual features enabled:
  - `--features=asset`
  - `--features=ui`
  - `--features=block_ui_interactions`
  - `--features=egui`
- Testing with various combinations of features enabled:
  - `--features=asset,ui`
  - `--features=asset,block_ui_interactions`
  - `--features=asset,egui`
  - `--features=ui,block_ui_interactions`
  - `--features=ui,egui`
  - `--features=block_ui_interactions,egui`
  - `--features=asset,ui,block_ui_interactions`
  - `--features=asset,ui,egui`
  - `--features=asset,block_ui_interactions,egui`
  - `--features=ui,block_ui_interactions,egui`

This ensures we catch any regressions or issues related to the features.

### TODO

- [x] fix all reported errors (without those reporting from `doc-check`)

### Changelog

- Add new CI testing for all feature flag combinations

### CODE REVIEW

**Comment by Shute052** [comment]
The new testing reports the following issues in the document:

```
error: unresolved link to `crate::systems::update_action_state_from_interaction`
  --> src/action_driver.rs:20:58
   |
20 | /// By default, [`update_action_state_from_interaction`](crate::systems::update_action_state_from_interaction) uses this component
   |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `update_action_state_from_interaction` in module `systems`
   |
   = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(rustdoc::broken_intra_doc_links)]`

error: unresolved link to `crate::systems::update_action_state_from_interaction`
  --> src/action_driver.rs:55:71
   |
55 | ...n`](crate::systems::update_action_state_from_interaction) for an example of how this is done.
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `update_action_state_from_interaction` in module `systems`

error: unresolved link to `Interaction`
   --> src/input_mocking.rs:[119](https://github.com/Leafwing-Studios/leafwing-input-manager/actions/runs/7970380465/job/21757867601?pr=475#step:6:120):26
    |
119 |     /// as well as any [`Interaction`] components and all input [`Events`].
    |                          ^^^^^^^^^^^ no item named `Interaction` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

error: unresolved link to `crate::systems::update_action_state_from_interaction`
  --> src/plugin.rs:52:48
   |
52 | /// - [`update_action_state_from_interaction`](crate::systems::update_action_state_from_interaction), for triggering actions from buttons
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `update_action_state_from_interaction` in module `systems`

error: unresolved link to `bevy::ui::Interaction`
  --> src/plugin.rs:53:[122](https://github.com/Leafwing-Studios/leafwing-input-manager/actions/runs/7970380465/job/21757867601?pr=475#step:6:123)
   |
53 | ...component based on an [`Interaction`](bevy::ui::Interaction) component
   |                                          ^^^^^^^^^^^^^^^^^^^^^ no item named `ui` in module `bevy`
```

**Comment by Shute052** [comment]
Or just check-doc with --all-features?

**Comment by alice-i-cecile** [comment]
Let's run doc check only with all features. I care much more about the links working on docs.rs than locally.

**Comment by Shute052** [comment]
In that case, this PR doesn't have any further actions needed, at least for now.

**Pull request merged**
