### PR TITLE
sync up macros dependency with macros crate name

### PR DESCRIPTION
**Pull request by shnewto**
Fix for issue #160

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Can you bump the version number of the entire crate by a minor version and prepare quick release notes? I can do it myself too, but I'm a bit busy and would like to publish a fix today.

**Comment by shnewto** [comment]
@alice-i-cecile oh sure thing, will just take me a few minutes

**Comment by shnewto** [comment]
oh actually, clarifying question for the version bump. would you like to see `0.4.1` or `0.5.0`?

**Comment by alice-i-cecile** [comment]
0.4.1 please :)

**Comment by shnewto** [comment]
@alice-i-cecile I think I covered it 😄  but I'm happy to make adjustments or other changes

**Comment by alice-i-cecile** [comment]
Merging! I'll cut a release quick for you once CI passes.

**Comment by shnewto** [comment]
@alice-i-cecile before you cut the release I have a question actually

**Comment by shnewto** [comment]
srry probably overthinking it, but were the changes to hyphenate the crate names released? or just queued for the next round... on crates.io I see the macros crate with underscores still

**Comment by shnewto** [comment]
yeah it looks like the top level crate's 0.4.0 is depending on the right thing so a 0.4.1 in this state might break things instead of fix them unless the macros rename is published 😅

**Comment by alice-i-cecile** [comment]
> srry probably overthinking it, but were the changes to hyphenate the crate names released? or just queued for the next round... on crates.io I see the macros crate with underscores still

Yeah, I couldn't change this because crates.io gets angry at me for having previously published the crate under a different name :(


Publishing 0.4.1 now.

**Comment by alice-i-cecile** [comment]
> C:\Users\Alice\Documents\leafwing-input-manager [main ≡ +0 ~1 -0 !]> cargo publish --dry-run
>     Updating crates.io index
>    Packaging leafwing-input-manager v0.4.1 (C:\Users\Alice\Documents\leafwing-input-manager)
> error: failed to prepare local package for uploading
> 
> Caused by:
>   no matching package found
>   searched package name: `leafwing-input-manager-macros`
>   perhaps you meant:      leafwing_input_manager_macros
>   location searched: registry `crates-io`
>   required by package `leafwing-input-manager v0.4.1 (C:\Users\Alice\Documents\leafwing-input-manager)`
> 

  
 Cargo please... I think the correct fix here is to rename the macro crate to the hyphenated form and publish that.

**Comment by alice-i-cecile** [comment]
> error: failed to publish to registry at https://crates.io
> 
> Caused by:
>   the remote server responded with an error: crate was previously named `leafwing_input_manager_macros`

Blah, I hate it. Reverting this change set and reopening the originating issue.

**Comment by shnewto** [comment]
😓 let me know if there's anything I can do to help untangle

**Pull request merged**
