### PR TITLE
0.14 compatibility release

### PR DESCRIPTION
**Pull request by brandon-reinhart**

### CODE REVIEW

**Comment by brandon-reinhart** [comment]
I'm confused about what you intend to do here. It looks like you want to ship a 0.14 that just contains bevy 0.14 compat and then ship a 0.15 that contains the breaking changes in main.

**Comment by alice-i-cecile** [comment]
> It looks like you want to ship a 0.14 that just contains bevy 0.14 compat and then ship a 0.15 that contains the breaking changes in main.

Yep, that's precisely the idea.

**Comment by alice-i-cecile** [comment]
There we go, I've swapped the base and the diff looks much better. If you get a chance, can you bump the `bevy-egui` dependency now that the [new version](https://crates.io/crates/bevy_egui) is released?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Leaving this open for now to make it easier to find. I'll try and get back to my PC to do a release this evening.

**Pull request merged**
