### PR TITLE
Remove Direction in favour of Direction2d from Bevy

### LINKED ISSUE #487: Use Bevy's new `Direction2D` types
## Which code could be improved?

The code from https://github.com/Leafwing-Studios/leafwing-input-manager/blob/cd7f795e2af1f3e68b292f30b2c1f1f8b335e8c9/src/orientation.rs#L493 can likely be removed now that Bevy exposes its own `Direction2D` type.

If needed, feel free to leave `Rotation` around for now, until we get a Bevy 2D rotation type (to replace Quats for 2D).

### PR DESCRIPTION
**Pull request by Ant59**
Remove `Direction` and replace all usages with `Direction2d` from Bevy, preserving all conversions and replacing usages.

Fixes #487

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Awesome, nice and simple :) Can you update RELEASE.md with this change?

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
This will need to be 0.14.0, since it has breaking changes. In the section heading, make sure to leave a (unreleased) note :)

**Comment by Shute052** [comment]
Seems like we could remove `Rotation` after Bevy's [`Rotation2d`](https://github.com/bevyengine/bevy/pull/11658) added

**Comment by Ant59** [comment]
> This will need to be 0.14.0, since it has breaking changes. In the section heading, make sure to leave a (unreleased) note :)

Done.

> Seems like we could also remove `Rotation` after Bevy's [`Rotation2d`](https://github.com/bevyengine/bevy/pull/11658) added

I'll open a separate PR.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Awesome, thank you!

**Comment by alice-i-cecile** [comment]
FYI @Ant59 this PR is based off your fork's `main` branch. You'll probably find it easier to keep track of open source contributions if you create separate branches on your fork for each new PR you do :)

**Comment by Ant59** [comment]
Thanks. It's just pure laziness on my end :laughing: I only intended to make this one change because I hit a snag in my own project where this is used. I'll create branches for future contributions.

**Pull request merged**
