### PR TITLE
Run clippy on examples in CI

### LINKED ISSUE #201: Ensure that all examples run in CI
They should run for a couple milliseconds each and then be closed. We can't verify correctness, but we can avoid runtime panics and compile failures.

### PR DESCRIPTION
**Pull request by TimJentzsch**
Closes #201.

Note that this doesn't _run_ the examples, but I think running clippy on them gives the best ROI.

Actually running may have several disadvantages:

- It's hard to set up, you'd probably need to get a list of all examples somehow.
- It could reduce CI times substantially, depending on the timeout.
- It is flaky, sometimes it might catch an error and sometimes not.

Also note that this way of setting up CI has the disadvantage that it's not run in parallel.
This might not scale well, especially with the examples now.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I think this is a good starting place.

I'm definitely worried about runtime panics getting missed (especially missing resources), but this is a sizable improvement and we can revisit it later.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
We should disable type complexity for this entire check.

**Comment by TimJentzsch** [comment]
> I think this is a good starting place.
> 
> I'm definitely worried about runtime panics getting missed (especially missing resources), but this is a sizable improvement and we can revisit it later.

I wonder if we can somehow detect those paper cuts at compile time in the future

**Comment by TimJentzsch** [comment]
> We should disable type complexity for this entire check.

Yea I think I forgot a `--` in the command

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
