### PR TITLE
Implement Reflect for InputMap

### PR DESCRIPTION
**Pull request by barsoosayque**
Currently it's not possible to directly use an `InputMap<A>` as an asset (e.g. `Handle<InputMap<A>>`), as `trait Asset` now requires `TypePath`.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you swap this to a `Reflect` impl instead? It will have the same effect, but is much more powerful.

**Comment by barsoosayque** [comment]
Sure thing. Didn't know `Reflect` also implements `TypePath`, but I'll try to derive it for other types too

**Comment by barsoosayque** [comment]
So since `PetitSet` is a foreign type, I had to create a newtype for it just to have a reflectable `PetitSet`, and then manually implement `Reflect` (and other reflect related traits). It doesn't seem like a bad solution, but one major issue is that `UserInput::Chord` is not a `Box` anymore (since `Box<dyn Reflect>` is not reflectable, [yet](https://github.com/bevyengine/bevy/issues/3392)), therefore it drastically increased in size and I'm not really sure what to do about it.

**Comment by alice-i-cecile** [comment]
Right, okay :) Let's merge this as is then.

**Comment by barsoosayque** [comment]
Um. so this PR is pretty much the same as #331 (although it's slightly outdated). And I've seen that there is an ongoing work to remove a `PetitSet` as a dependency, so I'm not sure what's the best course of action here..

**Comment by alice-i-cecile** [comment]
We should merge this and unblock this feature request, then remove PetitSet in another PR.

**Comment by alice-i-cecile** [comment]
I'm going to tackle this in #400, which should be done shortly :) This was super helpful to push me towards "remove petitset" as the right architectural decision, thank you.

**Pull request closed without merging**
