### PR TITLE
Add `value` for button-like inputs

### LINKED ISSUE #551: Add Triggerlike inputs that have a 0 to 1 value
## What problem does this solve?

I want to properly model the behavior of buttons that have a value from 0 to 1, like the triggers on Joysticks.

## What solution would you like?

Add a `Triggerlike` type (which implies `Buttonlike` and thus `UserInput`) which store this data.

## Related work

Cut from #548 for scope.

### PR DESCRIPTION
**Pull request by Shute052**
# Objective

- Fixes #551, #648
- Adopted #615

## Solution

- added `value` function and friends to `ButtonlikeInput` trait
- added `button_value` function and friends to `ActionState`
- added `value` field and friends to `action_data::ButtonData`
- `GamepadButton` and `GamepadButtonType` now get values from `Axis<GamepadButton>`
- `VirtualAxis`, `VirtualDPad`, and `VirtualDPad3D` now report axis values based on the values of the constitute

## Undecided Parts

How should we deal with `ActionDiff`?

This PR simply adds a `value` field to `ActionDiff::Pressed`

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
> This PR simply adds a value field to ActionDiff::Pressed

I'm fine with this for now, but I'd like to hear what @cBournhonesque would prefer.

**Comment by cBournhonesque** [comment]
I guess my questions is how does `Button + value` differ from `1d Axis`? 
Is it that we want to model the fact that the button can be 'pressed/released', on top of the button?

I wonder if it might not be better to create a new input type for those, since they are a bit niche. I would expect most users to expect a button to just be pressed or not

**Comment by alice-i-cecile** [comment]
> I guess my questions is how does Button + value differ from 1d Axis?

The valid range is [0, 1], not [-1, 1]. It's also used differently semantically.

**Comment by cBournhonesque** [comment]
I see; adding a value works for me!

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
